version: '3'

services:
  ffmpeg:
    image: jrottenberg/ffmpeg:4.4-scratch
    container_name: ffmpeg
    command:
      [
        "-i",
        "rtmp://103.130.211.150:10050/stream",
        "-c:v",
        "libx264",
        "-c:a",
        "aac",
        "-strict",
        "-2",
        "-f",
        "hls",
        "-hls_time",
        "10",
        "-hls_list_size",
        "10",
        "-hls_flags",
        "delete_segments",
        "-hls_segment_filename",
        "/mnt/hls/segment_%01d.ts",
        "/mnt/hls/index.m3u8"
      ]
    volumes:
      - type: bind
        source: ./hls
        target: /mnt/hls
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/usr/share/nginx/html/hls

volumes:
  hls:
