version: '3.8'

services:
  ffmpeg:
    image: jrottenberg/ffmpeg:4.4-scratch
    container_name: ffmpeg
    volumes:
      - ./ffmpeg_convert.sh:/app/ffmpeg_convert.sh # Mount volume for shell script
      - ./hls:/var/www/html # Mount volume for HLS output directory
    command: ["bash", "-c", "/app/ffmpeg_convert.sh"]  # Execute shell script using default shell

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount volume for Nginx configuration
      - ./hls:/var/www/html # Mount volume for HLS output directory